---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAtqkBnOWn1gD6JX0hH47arA5FSnUsBfSdYTI08QEhtzpWmiyHHD7VdXwxu90m0PTC1HtQrWgySX+I1u2iAS9QjZ13qpHWHAEDdCmCxg1+MdOWRATy39eBvSh+1U1+W5vEkJRU4EsWQlehA9A74ypoMhozJhQPmFMc6+UVy4yiSw8xF99w422k2OCT0P76gUvmEr/PQqYY9FQ6vAvcGBMpWD4pU8hoqQlsyJW22ns7/z9kvQZivcIgrNNO6qOHFvdABV2NngqtW0TbY1ZpQ5R7RYgPZlDPBoipmF1OLHrRjgectEfzz/u6EFEUNgd0mSvU2YtdLvb5NXDrMdber1jn+DCRLAKYoa8FaLLIJMaedRUbExmd65RMIzI1lJa265zXQfytyGU2BjLYvKBfwtHtPVQwSbBTVbKgT5omYI6thMdvoD6zs1Lq1nOufNCdZgdpj5KkpJYmChuzRHSqCU4kr0qzNPwqkHhdTXs3pBgVA5I2wqyARV9mc6wETRvSZa18Kl0K93DGK59zed7jXYMw65PmFZd5Vw8dd/nM/1UL1MGz8sP3n26VD34/wv5SJ4+1j/yOj5zVP1+wk7knBdAHrjsaq0pWsqejtTpo94NXtRaAPIqzWgUKFBB/hOTb6/r3PXDvpMtBHzu3GO2UxIdMwKiibS4GaWbXyMvEPhilMniy7p6AxzhMHhRH+otEH7baDuy8xz+MCpGQ+Q7ynaOe2oQabBfp619fqLcMWh75z0lWKDoDJCQZqPEz+IEI8n870CNlQhKMkTVF3CeEQ+PjDs03IL0v63bDkpeof/Yn3FIFiu1bPI6kSZcDFoIZo1YoiQ5AlpTBDsfBbj5ADHHxcaCeSjw8l1VSnq1nBz25qcc54cW3yTMXvo03dFzMToTjWhCxv901m9o+wihzer786Z88+VITQHmKXPdqL1i2BNPR/UIsvnLpl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: tunnel-token
      namespace: cloudflared
