---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-runner-registration
  namespace: github-actions-runners
spec:
  encryptedData:
    token: AgB18vkYGXTXgOd8gs1rPRVYCkpWsvqqDIsnqPL66RPuWIJp44QUyfmyy9pU0qWgZt28MMl0SjlDUb/Zr2knK7zZGNyWn63oomsCrk9YGcREN3WbDWKGXiZnL2m33BXTfdvrqyGW2kz9rwp2sMIRR6w0t110KgfgNua6U4Hw0iljf15EY2dPZwBtYxmr+TaMcdZiwzGxh3Bli0y5iMv8nEIjh52RIPhsKdSVqju/c7cOBY3ABoKm/czE15/Ff1gyPjRtl6A9vm3ZWt3JyqDg9HXMG/yMTbpiiAXKvq9Xi5UubwbkJx0ABUiTYR9GCZFyHwe5YkQM62MRquyGblZMu7k4S5F5MtorDJ1wVcUCoRgTJ39kC9JPyBx/B817w8oalokLbbP/5YRz4FykXWT761AU0Xc0mGQXXw4KZfAPTc4lcF/tWarFXKfE8HNdTUr0Om44RtHtJebvtSqsjEhR3bmpOUUSsJjFve//GrWelBJRrMIKquwqmHddFIktzsQdNmiEC2hVJ1pTMl00XYX9sOof0rWK9igIOGGRNPIWCXcYmRDvaqugNKnGBANb97qDrfx7MHwJWMVVU3O/fhTvGYRlrmSK6AxHtHCVxCpTpbDaVmEP62/zqJigd5fHTHO5d4c5zFGW8W6BGdfXYD/8nEK7S4qPmvOXNZNCGaWJqm3gvrXdmwMHVKCZ6vtr4MLK8Tmv8tTVKOYqeBosWPd2x/UiB2PGm3bhpJNHglh33g==
  template:
    metadata:
      name: backstage-runner-registration
      namespace: github-actions-runners
