---
apiVersion: v1
kind: Secret
metadata:
  name: samba-credentials
type: Opaque
stringData:
  ACCOUNT_homelab: "ChangeMe-SuperSecretPassword"
  UID_homelab: "1000"
  GROUP_homelab: "1500"
  GROUPS_homelab: "homelab"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
data:
  TZ: "Europe/Warsaw"
  WSDD2_DISABLE: "1"
  AVAHI_DISABLE: "1"
  SAMBA_VOLUME_CONFIG_data: "[Data]; path=/shares/data; valid users = homelab; guest ok = no; read only = no; browseable = yes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-shares
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      initContainers:
        - name: init-shares
          image: busybox:1.36
          command: ["sh", "-c", "mkdir -p /shares/data && chown -R 1000:1500 /shares/data || true"]
          volumeMounts:
            - name: shares
              mountPath: /shares
      containers:
        - name: samba
          image: ghcr.io/servercontainers/samba:latest
          imagePullPolicy: IfNotPresent

          envFrom:
            - secretRef:
                name: samba-credentials
            - configMapRef:
                name: samba-config

          ports:
            - name: netbios-ns
              containerPort: 137
              protocol: UDP
            - name: netbios-dgm
              containerPort: 138
              protocol: UDP
            - name: netbios-ssn
              containerPort: 139
              protocol: TCP
            - name: smb
              containerPort: 445
              protocol: TCP

          volumeMounts:
            - name: shares
              mountPath: /shares

          readinessProbe:
            tcpSocket:
              port: 445
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 445
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6

      volumes:
        - name: shares
          persistentVolumeClaim:
            claimName: samba-shares
---
apiVersion: v1
kind: Service
metadata:
  name: samba-lb
spec:
  type: LoadBalancer
  selector:
    app: samba
  ports:
    - name: netbios-ns
      port: 137
      targetPort: 137
      protocol: UDP
    - name: netbios-dgm
      port: 138
      targetPort: 138
      protocol: UDP
    - name: netbios-ssn
      port: 139
      targetPort: 139
      protocol: TCP
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP