---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-session
  namespace: backstage
spec:
  encryptedData:
    secret: AgA1L4NhwLl4BmVqXXj1tuuSq7fR6vNFH/sFMsN+SgsArNtHFOVBgoLRhWWC/dZ9uw3k+ECneQspEAEUfXS91AxTQU3WMArfogMbHwtmtpm40d/fLexjvrGvvHfCfsMU1Ogl/xHcz9EZk+tR+zlAfvF5iU0WFc8DmwIkTKwOGKfms2gNwjjxrLJn4pbtkedmGYp+LR7+M0V9aQZqeN0x8/NZW04D9GXHmqkDRyHo8pbaaDtpJ0hcFmhKO3IYdj0QSKavlKLl1FSe7dFidrJVqW+bgvB0JbFxEOcV3pD+z/rCGOQKdoKOQK/CELo1RvKJ67oWpgbIqIcosz2yTfrvoESqjmCUuINwExHvTtVzpHNWxrQSk9oVJEpJlFoBbW+1J09PYUXWxEkWzIJ2xjM9YmCog3lsgyCYmhlBqSUFsEkye9ST3S/227HMD5MVS7AGz6grrhW+Jg5mYaYch1ke1+RIsn1M5DQLEcDrdvWqcg1Kss4caSz0kFrwh+3XC/+ZsbZMoZDMdB/k7f9tFX9ptDz3QVTZsW3jHDQVpqPBvBQ13LLyZRLSRQML/xPNk1bslcDd8HxQum92ghTCYkjtROhMF4tid981wO+ikZgPjijaRap9Py2u6NQ2epJJBTzYZUqH7xiWToiwF9qQmh9FoEz7NQ+BCoBCnM58aYhR/mUGzh+ryFElGij63x4pztTEiDKbaUIJyooyhSsRFX7jv8gaR+9DaQBCXrdL+a+TocJcAEdl1oQpX0JezA9mNlHzZ/g/4vnIQL1A0aI/x+ESHhi0
  template:
    metadata:
      name: backstage-session
      namespace: backstage
