---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: argo-workflows-sso
  namespace: argo
spec:
  encryptedData:
    client-id: AgBTO0hg0dY5xJh1fJd/ynTr91iF2jeRVy+eK5W37pYmlpcqa9+cJhxDisfVtzfRqeSNLDN7wk30f4YUouqDv4QH6YQoBWyjdsNcKGDR7kpmRn80wBdz1TbQ5jKp2wqs9oKWN0GGr4eFtIZ1sT2zjZXOWNREcSyj4zYtsRisR03c96nje6+QII2CBVtKzwK3tzxh2oZ/PPrhlPDAK2WBjPfmkshdx/WFLgufKPPq/zDWT0jpc4/cK2E2+wFXOJCWxLqLVbsnV5l5uYFOagKaJAO15d0o2NHlI+p5qbh9hfERul+EnPfsZ3xa1GSxTmzp32ab/6j+Nhg17bKVUW8SBDeH9Xc9+4IEKabAGOfZVP2Gk9vNF3Q6GHmM4d+bH0Fau0ul2t8gqnZtLl8K+rJc1lMpoDEoMd9oj+SOvyREr0w6LL5bQjP8Ir+loZFE5WuEbOsBFNYJJblT3FCTiNrZrcYXcubFO9n28hN9KfS+DZz19qkMWYqrrhI1JiQSu9s8qIFvk+w7KTEhgdtVZoYnVNzdFOuEn5O30Vq4XTi4uZHIiKKvxDOEM9xF21Zl1OENDDorvatL9ffa+LAoBd+1yl4uQWul+XHs+Ta1ntLnyhNiJWvbZh1Ha4VOg0zQ+88c8UkiDIqbgejDOqvL92UO6NinYqdCKCHFag/QMUx1fP+PfDJNUdtKuF2FwPB2gL2nsePOpugPcXobDW5QR1drdo+1mX8=
    client-secret: AgBhxh+3LmLmRcFEN16iAxC/sYjDV4BZYkCXTQeS4RLqBv8oh4ZgM/FOznfepOdzFmLb0MGVAcBXFi6j+3WCx7Uh7NLeVZMIVLYYpj3033qT9rn6TOyCDs7DwIEiKfgm8YZ8tM85cPu7XBAbRRp3tmWf/bzA89Gs/Y8PcUnCv3+QNjrPg8aYRyo2PMZ3iRU9+QUyH1yUvANFER8HHPdU5ojitaaslxajGLoYjf0X2Kxa4xEhj/yoi9Gxz5H5zmpWV592H4tgWSyxvyVQEynCfufLrtTX7kIvjzhGGPAwOhHUnnCNlhG0cv+dmt/ilGjGef/MIO695ZDqRKSUMAUN1PVzhsGOQbZRnz+sN02Zyo08nOVdjNlYAZjnLeB1MHvx0am1axsuHt6kx7LWjVNiXuH7L+MJ6Pd8T0KYRs6f7IvVMJJwT1P8IRNd0j+i0LV+RrDs2rnthvt7BZQvq+awj++zKg3iJoFpUjL4F1Qj0b0iODuArtvstuvSEDOF+xLEthOV/D57csmTtpTnyk+/L3iLidRkyaAFp+jNEFl7F51N+BD9AeaP34WAuI5rT8CgoS+VMWmV1sYrfMlXPlxIEo5l9IWQVXmsVDXYPPBSmRoUC62Iu1sL0PqLMYoXg9eaOgZLUYtxb24uq8YTdl/xeEEOhswIcCmGAcE9dZ6xS/mhCCqTyksd3/9OzeXMBMvcL6+9iaxDVAUhrxJH8A9lJN+SiJ0d7Qhg+ED9bINuYBBKMw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: argo-workflows-sso
      namespace: argo
