apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-only
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: read-only.service-account-token
  annotations:
    kubernetes.io/service-account.name: read-only
type: kubernetes.io/service-account-token