apiVersion: v1
kind: ConfigMap
metadata:
  name: directus-config
data:
  DB_CLIENT: pg
  DB_HOST: directus-postgres-rw
  DB_PORT: "5432"
  DB_DATABASE: directus
  HOST: 0.0.0.0
  PORT: "8055"
  LOG_LEVEL: info
  LOG_STYLE: raw
  MAX_PAYLOAD_SIZE: 20mb
  PUBLIC_URL: https://directus.example.invalid
  STORAGE_LOCATIONS: local
  STORAGE_LOCAL_DRIVER: local
  STORAGE_LOCAL_ROOT: /directus/uploads
  TELEMETRY: "false"
  WEBSOCKETS_ENABLED: "true"

