apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: directus-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  bootstrap:
    initdb:
      database: directus
      owner: directus
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  storage:
    size: 10Gi
    storageClass: proxmox-data-ext4

