apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-valkey
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-valkey
  template:
    metadata:
      labels:
        app: immich-valkey
    spec:
      automountServiceAccountToken: false
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:9@sha256:70739f85ad2ee01a726a965584a0f94895f01b0c60b3cc8b0aeef11eaa6888cf
          args: [--appendonly, 'yes', --appendfsync, everysec]
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            exec:
              command: [valkey-cli, ping]
          livenessProbe:
            exec:
              command: [valkey-cli, ping]
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-valkey
---
apiVersion: v1
kind: Service
metadata:
  name: immich-valkey
spec:
  selector:
    app: immich-valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
