apiVersion: v1
kind: Namespace
metadata:
  name: pocket-id-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oidcclients.pocketid.dev
spec:
  group: pocketid.dev
  names:
    kind: OIDCClient
    listKind: OIDCClientList
    plural: oidcclients
    shortNames:
    - oidcc
    singular: oidcclient
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.pocketIDRef.name
      name: PocketID
      type: string
    - jsonPath: .status.clientID
      name: ClientID
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              applicationURL:
                type: string
              clientID:
                type: string
              clientName:
                type: string
              pocketIDRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
              redirectURL:
                type: string
              secretName:
                type: string
            required:
            - pocketIDRef
            - clientName
            - applicationURL
            - redirectURL
            type: object
          status:
            properties:
              clientID:
                type: string
              conditions:
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
              observedGeneration:
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pocketids.pocketid.dev
spec:
  group: pocketid.dev
  names:
    kind: PocketID
    listKind: PocketIDList
    plural: pocketids
    shortNames:
    - pid
    singular: pocketid
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.url
      name: URL
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              apiKeyRef:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                required:
                - name
                - key
                type: object
              url:
                type: string
            required:
            - url
            - apiKeyRef
            type: object
          status:
            properties:
              conditions:
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
              observedGeneration:
                format: int64
                type: integer
              openIDConfiguration:
                properties:
                  authorizationEndpoint:
                    type: string
                  issuer:
                    type: string
                  jwksURI:
                    type: string
                  tokenEndpoint:
                    type: string
                  userInfoEndpoint:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pocket-id-operator
  namespace: pocket-id-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pocket-id-operator
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - pocketid.dev
  resources:
  - pocketids
  - pocketids/status
  - oidcclients
  - oidcclients/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pocket-id-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pocket-id-operator
subjects:
- kind: ServiceAccount
  name: pocket-id-operator
  namespace: pocket-id-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id-operator
  namespace: pocket-id-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocket-id-operator
  template:
    metadata:
      labels:
        app: pocket-id-operator
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        image: zot.homelab.kszpakowski.com/pocket-id-operator:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: probe
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: probe
        readinessProbe:
          httpGet:
            path: /readyz
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: pocket-id-operator
