apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xwebapp.github.platform.kszpakowski.com
  labels:
    provider: github
spec:
  compositeTypeRef:
    apiVersion: platform.kszpakowski.com/v1alpha1
    kind: XWebApp
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: repository
      base:
        apiVersion: repo.github.upbound.io/v1alpha1
        kind: Repository
        spec:
          forProvider:
            visibility: private
            deleteBranchOnMerge: true
            hasIssues: true
            hasProjects: false
            hasWiki: false
            vulnerabilityAlerts: true
            template:
              - owner: kszpakowski
                repository: template-go-webapp
                includeAllBranches: false
          providerConfigRef:
            name: github
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-repo"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.name
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.name
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.type
          toFieldPath: spec.forProvider.template[0].repository
          transforms:
            - type: map
              map:
                go: template-go-webapp
                node: template-node-webapp
                react: template-react-webapp
      connectionDetails:
        - type: FromFieldPath
          name: repositoryURL
          fromFieldPath: status.atProvider.htmlUrl
