apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsu
  template:
    metadata:
      labels:
        app: rsu
    spec:
      containers:
        - name: rsu
          image: zot.homelab.kszpakowski.com/rsu-espp-dashboard:latest@sha256:e72c06df87c08a08d3ac18cbc1aa2e3a2533a96836660cbaaa0710f7d614b60a
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
