apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
        - name: crm-main
          image: nginx:latest2
          ports:
            - containerPort: 80
          # env:
          #   - name: DB_URL
          #     valueFrom:
          #       configMapKeyRef:
          #         name: db-config
          #         key: DB_URL
