apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: crossplane-apollo
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: crossplane-apollo
      spec:
        template:
          spec:
            containers:
            - name: apollo-syncer
              volumeMounts:
              - name: etc-ca-certificates
                $patch: delete
            volumes:
              - name: etc-ca-certificates
                $patch: delete
              - name: k8s-certs
                $patch: delete
