apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backstage
          image: zot.homelab.kszpakowski.com/backstage:sha-fd781c36d5273411bb53f56d4e5176ea10ccae0c
          args:
            - node
            - packages/backend
            - --config
            - app-config.yaml
            - --config
            - app-config.production.yaml
            - --config
            - /app/homelab-catalog/app-config.catalog.yaml
          volumeMounts:
            - name: catalog
              mountPath: /app/homelab-catalog
              readOnly: true
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: NODE_ENV
              value: production
            - name: POSTGRES_HOST
              value: backstage-postgres-rw
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-app
                  key: password
            - name: AUTH_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backstage-oidc
                  key: client_id
            - name: AUTH_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backstage-oidc
                  key: client_secret
            - name: AUTH_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: backstage-session
                  key: secret
          startupProbe:
            httpGet:
              path: /.backstage/health/v1/readiness
              port: http
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /.backstage/health/v1/readiness
              port: http
          livenessProbe:
            httpGet:
              path: /.backstage/health/v1/liveness
              port: http
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      volumes:
        - name: catalog
          configMap:
            name: backstage-catalog
