apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: app-2-role
spec:
  forProvider:
    name: app-2-role
    description: Role for app-2 service
    # assumeRolePolicy: |
    # inlinePolicy: |

  providerConfigRef:
    name: aws-provider