apiVersion: iam.aws.m.upbound.io/v1beta1
kind: User
metadata:
  name: app2-user
  lables: 
    service: app-2
spec:
  forProvider: {}
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: AccessKey
metadata:
  lables: 
    service: app-2
  name: app2-user-access-key
spec:
  forProvider:
    userSelector:
      matchLabels:
        service: app-2
  writeConnectionSecretToRef:
    name: app2-user-access-key-conn
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Policy
metadata:
  labels:
    service: app-2
  name: assume-role-policy
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "AllowAssumeRole",
              "Effect": "Allow",
              "Action": "sts:AssumeRole"
              "Resource": "*"
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: app2-user-policy-attachment
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        service: app-2
    userSelector:
      matchLabels:
        service: app-2
