replicas: 1

deploymentStrategy: RollingUpdate

image:
  repository: upbound/xgql
  tag: v0.2.0-rc.0.175.g0fa8ed6-main
  pullPolicy: Always

nodeSelector: {}
tolerations: {}
affinity: {}

# Uncomment to serve via TLS.
# tlsSecret: xgql-certs
# args: {"--tls-key=/tls/tls.key", "--tls-cert=/tls/tls.crt"}

args: [
  # "--cache-expiry=336h",
  # "--help"
  "--debug",
  "--enable-playground",
  "--listen-insecure=127.0.0.1:8080"
]

# imagePullSecrets:
# - dockerhub

priorityClassName: ""

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

securityContext:
  runAsUser: 2000
  runAsGroup: 2000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

metrics:
  enabled: false
health:
  enabled: true
