apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-mcp
  template:
    metadata:
      labels:
        app: argocd-mcp
    spec:
      containers:
        - name: argocd-mcp
          image: ghcr.io/kszpakowski/mcp-for-argocd:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ARGOCD_BASE_URL
              value: "https://argocd.homelab.kszpakowski.com"
            - name: ARGOCD_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-secret
                  key: ARGOCD_API_TOKEN
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
