apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-key
spec:
  encryptedData:
    apiKey: AgCU0iVCZM9PP/g6UZ/MNJUdl3D4Ka4rlW2zSOInOuiJmOIN0OArDcDnnFoTVSs8xAGB91mgd86MdJ7wzuXG4DGJhRSpLklun8EHA9JcU/V1VyZ/UxBfq1Gyiqf5lJmFA4EixPlZz5pfq1NPa4+XBCegQj38qahB5PVRpkLrFBMkNkzDyXbK2h+Yx2UeoIEntORotIYgXjy6GUQQcqu2JwGS9LUAVi3cK+WnxZ5cfO8rJ8qrA25uUYOSE9iskK1eSdjZg6WAuZsVs1XrJ3hmIxZIOcbr7NrVqTWbnzOyDdcuICEPeboRsFlNiaEpKImV3tg3NDtbzbtnOq3Uwd+T1xanbSctzm7h2aRorv/+xwsn5GoBxx8yLTflNuT7hIwJPXWELTRLXt/wXxDp+9njSw+6XCKiTIwCXVXOEVZqqjCpDc3IRxP2IuUuctoPAXt5w/6dADRJ1T9+0D+KMZIQPrgAXq1nW7Uu1yN8twBQnvjJ7tTQ9t6NInh4LxTVWkcGkHZKW4mUuWRNgJ1c6ItAo1f4qNChFPg0XZFaqv284yZUECz9ZuQBUBQl8FOwvXgnQcO2TrdlysD2KbV4P2/X9YTTmniUc3ajd3Z08d18XWSdPHjqhr+afylqvUjhUebxaNP6tp4/G1KhMnbwHV7LyAQDDukanUwLCSeYUt20tX13r1vFIHIoyZ+7wvhq3V2t/D8kWUYf3hMy+361k5xHX5+hAJi/d5Q9nqugE9sWGI0kZG0ksDBJTFUX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-key
      namespace: external-dns
