apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: upload-server
  template:
    metadata:
      labels:
        app: upload-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: upload-server
          image: zot.homelab.kszpakowski.com/upload-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data/uploads
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
---
apiVersion: v1
kind: Service
metadata:
  name: upload-server-lb
spec:
  type: LoadBalancer
  selector:
    app: upload-server
  ports:
    - name: api
      port: 8080
      targetPort: 8080