apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - bootstrap-admin-sealedsecret.yaml
  - runtime-secrets-sealedsecret.yaml

patches:
  - path: configmap-patch.yaml

