---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: directus-runtime-secrets
  namespace: directus
spec:
  encryptedData:
    SECRET: AgA37Ywq5qeGeefiDivI6NLCF81wgAOd+ryXeOkXsb7TNW5Ik8G7pHdzPITdo4vs0Z1Ge+y9WfzESv/EMa+5WfDRWNeAUiVUoqvMTEkdOPfaS+pJ2EByzBzLtyoY0MtN6jqx2N3eY0KRfLgsX90KWlm3TQyYuP39E+mzWRwQDqXGPt8rn5v2bHHwZIpAOl+jLJq2rMktVCu8urWBXIoOPrjRzDBUY6t9pe+aUvnZI4WO+HgJCMHkUI9FrpYpIZT1MNg7XT+xOhuV0zqn0UfO00CEWpAL1FrfX2WKZsl/00TJHPn8ntSDBPkBffWg8v5g0MP0aLHzyay7Bz42rfdG7TarKHqPVU8zOSjPQGITpVmcE4PGty2SIVpoJP5d7jCPcYqsOJrwSX74Gs6qSlDhMHWs9yXMSu3+XAbQtBQgwBGh1duKtQ6LgBibznFH1cjixy06qweHwX9/4BjcVQrhglwfGxHjWdD4pIod8yAZDbZbp2UcZbPXV8VDN7Cj5o59XT8vXGLHqRgcm3tTJVIL4FBn7ABKu9mfJLs8CmnhrV5Aw9stIjLzK5Sc+bDgB1DRZLK9uvX8wHGlIId+YUqNcIrLjLkpuYEgiEem0eZf93oqfh4qUZTDKFnQE74vzn0BSmNyigJWl57cmpujZRs3dBdJuD0ltwXbgQt1q4/7k5nf+xhCscB8e8Di0bLTs2GFPeCLS8yZBSQtnxbVLbsoKExX1EQ0JSDL8wuexazjGN22eKsNn2sErEwvITJOR0QB7EjGAlsLvFxAmUd6ViS4LThf
  template:
    metadata:
      name: directus-runtime-secrets
      namespace: directus
