apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: backstage-
components:
  - ../../components/runner
labels:
  - pairs:
      app.kubernetes.io/instance: backstage
    includeSelectors: true
patches:
  - target:
      kind: Deployment
      name: runner
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/secret/secretName
        value: backstage-runner-registration
configMapGenerator:
  - name: runner-config
    literals:
      - GITHUB_REPOSITORY=kszpakowski/backstage
      - RUNNER_NAME=homelab-backstage
