---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgAP1bbS4Vm3UiUKLhYN30L3OW6MeUPhk2Jvfqrmphq2AYvbtssn/NYoPD/j5qimlgeRzRtKinnAmusoGjBF+8YO3fekUxVbM1+eZh4GwHxLkq+FtKib18fdC0pQ+yZLkL6EuxMaEYu479MyUH3pyuJJzJpUza/0iGIRz4Ok/RMlayPOAhhkIVQ46ivnpwXM2sq6LGXRU6hJNFjduryM+gffz1opWS53oOvSYFTWqVNVgZR6923ULHuJP8JRtYF+Lpc5dDbqK66zns2H2rwgT5d+FaAgG7oUH+0mTW/I6ig0HwW7Xfc0ZnYZ15vrCR/Fp8b4+G5/Io+5r8qCUXv+jAbbq47UvryWfFs813Z97ieXyGX55Zrnj/fle361y/rUS9yLOagPM+tzdfyztXNUTFGrs9RMDPCMKQwGIcpRmryTjXN00McnHTOF9/xC/np7OIl/guNYtIgcj0RFIHQtSBVHCtNZiPn29TTvbSjS46CMVUGxQgfQHk+3xAaMCAos3lT6Jij8lcfjdXMEW37cFKX7qZO2zq3JVZeBbPnYV4lAaV7g0YvrCvrmJoBrgV17HIhnX7CJWeV8VVnmFdt5YI2LLxRcolcLfLzhS5IjIfjiF5EAb+VTI8DpoOtX0+Ts8qYFWpaFnqoV5QWtEYn2j2iryuV2rP7A0Fl6BUMS/t1dQbOlDWOmObtnnIwiBecTnWyA/ahMlKdi7fKXa7S+Tk/JVxE=
    client-secret: AgBHkgbsafRmDi2+EjHyxACEUpPjt5g4kOODCEISw7URjWuLQo4Od0khU8t07/N55BqCOegiHtYVGffsKK0Rop+Cp9pp5yjBtTDH9L/hY6ZfZA1HJNAcSfbX2SwoThp6T7ahY7Z4E7IcpT4WKrohglD1O6A5gCPd1KW6TBK+RjR7/yNcXel+4DoLext3+xeFLu6vBJkCC9eupZUzrT3mH9k4W+xb5VZfJ9xvK16ftTDCDBSdUGmL2c1dvwKl0RAh/ojOTike5jKFnVYEunNfhsKMtOu2kU/QPZElxz8oprtzncIj/4edinmsnQOgh37H5ykmrfiFUqs8b3HRHpoYmtKKyjX3kFRugBuYA97ELhCOxT9SYItxxSvtCYE612tsiV2+ZRPGN6zUj3vbzQIvAMEoZpCqtniCOXkqLlO3bL3+ZjE94/6hBrq/prKAxVDEwmCVLB7+gLfPpjulSRehvZXxj+k7nlYbqO2ol3iq23yR6VkAhsjudY/Y2gb0ooUqoGJSkOmea+KQWvCOWrKpOfQnvIoC7+PA2bEcz3vpYYrqFe98qw9a1AWQSoxH0ynBDiY6Y9E5eynXZzbzBGRvDlPMbUCkzqOIZiMU6uJU7zgyi+1ny0v/8wwxzZQwg0KB8lL17aAQDVCbQ+sOLV1ZuvK8XOd8AGmVYlSEg77bsBfne6aoKAdIEN4iUWkiR/yBaKuBUOUSrwyWIskoXZFwKGhUa6YKZKWNH6r7KaeiHLx2ag==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: argo-workflows-sso
      namespace: argocd
