apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.homelab.kszpakowski.com
  admin.enabled: "false"
  accounts.mcp: apiKey
  kustomize.buildOptions: --enable-helm
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: e2ae5b8b705e0c0f16c7
          clientSecret: $github-dex-client-secret:clientSecret
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - https://workflows.homelab.kszpakowski.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET