---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: github-dex-client-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgB+dnoj+sUfu8iO5/gO1rG7rKbHhGlthl4k+SHr320ggLrIxqSUcSmX7u81HPaFS2edjmogHVL8R83Im3BgipRVSG+NKNm1ph2P5XHMYWkSykanHxSPoBaCgmvxzD/8FBN6M4hla0EmnW5zKdVHPvO7sBw4WnWtDQ8cqiyJhxoUW0pdt9ILTJTKsmR97gg3lzSrD70t1l5yrH4TsJQnrB4u8RtrAgQaq1veSWCAWXS1ctiQGB3PR2mqvZpLOgbMS4Iu+3Z9ICE6KrAmkFOO9APL8ECrMdsmp656EoX1FGQSxB9vPW+CyjckBNzuazwNwiJwb8Iy3oLURH+6Vi9w6zL8gCZPpTzLYlaOthOv6kHCagnqj5wVYls8B/5m6Y2NgwdWs2HpE4QYx71rvUBNFaPkWWd0LmWZXfaEi4TLBg7+n72yVwoaFyTd2k6qT++4dm3qtO/sUBfNwmqNEzMK3iLW3kOe7wMyu7+PGUokEglHTjfm1pXpkq7DCxWgKqcaqJyPKDDrrOoewDitMTJIsNC1HW9/Ra0mDQCF6rMIPFgjJnaj9Qxc1CidPfEu8hbkZnfgdWn0/em7DN6xkno/9Z93AR469nsbkKLRrC/8PA7GO1Mq+Hfybvmg3uj8ILCUSr/zy5iGIjWyTZviFoyXpWGJYCpOUamuuos4cK+pCXXFcuSyGEBPhl4l8rbHP7Ki4VyCC50ylsT0kuuuzt43tH3oMUr0tgcwlbiZRFlEIK5mPT01CkgpPvng
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: github-dex-client-secret
      namespace: argocd
