apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  name: argocd-server
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.homelab.kszpakowski.com`)
    priority: 10
    services:
    - name: argocd-server
      port: 80
  tls:
    secretName: argocd-tls