apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.0/manifests/install-with-hydrator.yaml
- ingress.yaml
- tls-cert.yaml
- github-dex-client-secret-sealedsecret.yaml
- argocd-hydrator-secret-sealedsecret.yaml
- argo-workflows-sso-sealedsecret.yaml
patches:
- path: argocd-cmd-params-cm.yaml
- path: argocd-cm.yaml
- path: argocd-rbac-cm.yaml
- path: dex-server.yaml
