apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/argoproj/argo-workflows/releases/download/v3.6.5/install.yaml
- ingress.yaml
patches:
  - target:
      kind: Deployment
      name: argo-server
    patch: |
      - op: add
        path: "/spec/template/spec/containers/0/args/-"
        value: --secure=false
      - op: remove
        path: "/spec/template/spec/containers/0/readinessProbe/httpGet/scheme"
