apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vm.yaml
  - ollama-service.yaml
  - open-webui-pvc.yaml
  - open-webui-deployment.yaml
  - open-webui-service.yaml
  - open-webui-ingress.yaml
