apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.45.12
      chart: argo-workflows
      helm:
        valueFiles:
          - $values/argo-workflows/values/values.yaml
    - repoURL: https://github.com/kszpakowski/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/kszpakowski/homelab.git
      targetRevision: HEAD
      path: ./argo-workflows/manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
