apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  sources:
    - repoURL: https://github.com/kszpakowski/homelab.git
      path: cert-manager
      targetRevision: HEAD
    - repoURL: https://github.com/kszpakowski/homelab.git
      path: cert-manager-issuer
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true