apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distribution
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jfrog.io
      targetRevision: 102.30.0
      chart: distribution
  destination:
    server: https://kubernetes.default.svc
    namespace: distribution
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  