apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distribution
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.twun.io
      targetRevision: 2.2.3
      chart: docker-registry
  destination:
    server: https://kubernetes.default.svc
    namespace: distribution
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  