apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: alloy
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: "0.12.5"
      chart: alloy
      helm:
        valueFiles:
          - $values/grafana-alloy/values/values.yaml
    - repoURL: https://github.com/kszpakowski/homelab.git
      targetRevision: HEAD
      ref: values        
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
