apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: "0.6.26"
    chart: localstack
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
