apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: "0.6.26"
    chart: local-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: local-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

