apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-id
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kszpakowski/homelab.git'
    path: pocket-id/overlays/homelab
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: pocket-id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true