apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhooks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kszpakowski/homelab.git
    targetRevision: HEAD
    path: webhooks/overlays/homelab
  destination:
    namespace: webhooks
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
