apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhooks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: webhooks
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: oci://zot.homelab.kszpakowski.com/webhooks/webhooks
      path: .
      targetRevision: 1.0.0
      helm:
        valuesObject:
          env:
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: github-webhooks-secret
                key: SECRET
    - repoURL: https://github.com/kszpakowski/homelab.git
      targetRevision: HEAD
      path: ./webhooks
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
