apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhooks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: webhooks
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: oci://zot.homelab.kszpakowski.com/webhooks/webhooks
    path: .
    targetRevision: 1.0.0
    helm:
      valuesObject: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
