# TODO migrate multisource to kustomize overlays
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhooks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: webhooks
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: oci://zot.homelab.kszpakowski.com/webhooks/webhooks
      path: .
      targetRevision: 1.0.0
      helm:
        valuesObject:
          image:
            pullPolicy: Always
          env:
          - name: AWS_ENDPOINT
              value: http://localstack.localstack:4566
          - name: AWS_REGION
              value: us-west-1
          - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: webhooks-user-access-key-conn
                  key: username
          - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: webhooks-user-access-key-conn
                  key: password
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: github-webhooks-secret
                key: SECRET
          - name: SNS_TOPIC_ARN_GITHUB
            valueFrom:
              secretKeyRef:
                name: webhooks-github-sns
                key: arn
    - repoURL: https://github.com/kszpakowski/homelab.git
      targetRevision: HEAD
      path: ./webhooks
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
