apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xgql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: xgql
    server: 'https://kubernetes.default.svc'
  source:
    path: xgql
    repoURL: 'https://github.com/kszpakowski/homelab.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
