---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    API_TOKEN: AgBNf8x6CGzubou2ekoNpo+bXAmWlDZnJoVpUj/el4kKi8H2fwFvFUxTvNwB5Oe3Vb0hPJaaOL2EDrCS+9xx3tg8k8wpBUmZ975iPHh7lUeiDe7pKu5+OLM8B7ZOvohoh8Qyv3S7W65e1JY0sfR1TWdZhYU7toZ9nDLozJxSQP4Xf71xss4ncQZ9CC/QjiIdYRAL/nwD8nLto65RZO5vSZHF97djGTRaGn0QTh+uueKlzJERFV3uc4tJh0JY/K38BeAXhSlfVaT5Ozn2RxlV0MiQG36gidc1msY5NiDyagy6J0pdJ3BcnzPHsGEF7k0+lPI/FtuoyFRAbvzkftrKQWcdEaxzBLUx1K3i1XXK4y73khjIuBcz8oYCjiMEZgNF1CIrreKz+7iIQNjBNZsR13xVhRCKyPkhInUR302Tm5vgx4bHojZioh7TbC8aGqhsws6WeSfmoY76CTR8PQ666mVOMuZYw+65wlKJWWVerAk3RiJWop5AFS58rcOUjjxBoiH+U5XobAQUVp82v8PMx+AcUUSASqF/UjY1Uk9RH2Z/vu1SIVqKpwxCOA+P1JQiPy9S1FcMMB7zxsYMNSJe477SWJENrTVCYSTLobcWWEKpoy9i6HDfKrHaOalDNWOwCw7Fep8BeMlxd7kWfC8trJE0vDw4v4YxtZYlVdJ38XwNgT9pI7NBm3ZuNfFQYDicLOoEl/xxd1K/i7658gk20fokukuOH7mJmS3tDDoV2+ALK6MshL03TAYc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-token
      namespace: cert-manager
