---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    API_TOKEN: AgA3mizUppBUElPT4e2h5/U61YUALvPS4Zq8SvssJt//odP5Q99hNh/LiRtI0NAMDk5freoP57wYD3La9eExhtDkwtgQKfOMnd/Zmfst1ypAjCaNwgxhYOtV0NvlY+rTQ7OGspQCD9NTNj04/NaI487FxDMztaT7gISJvQdEijdUPW9uo3GETYX3pNNe/kwdiNOe+hJzq68axSLGxPm0jGPglWnqYwxIOd5Mai4T+sYQX3njBabVLpsoOGjfRdQPC1UU+o4TKBOpLfzKvAl48rrSwL5gPfO+Ub1E2QwD6o5ijcM4LNNb5DsJ6qbH83LprxCELL7k3bpZHYK2jFxdCJqN7RtH29wWK/ZqxbZGg/Yx3mD9FqC2vrumO23yCUT4CSRF6x+C6Ya7Xwb/W77liWmHHb8Em/ZuVuHKgUz659nHix6wG7PdohKQcLuML6+stLF5Iiuumjd44JiT3+n5kZFOhAlEYzjX1ZGvD7fu3CmwjftH/aaMpJ6gy9ls7/W3ELAhtUT6OpIlai1VfJpPOmE47vUx5ZGlcPL8k3cYDhvYX/hpv/Hy2EWcFydfpIyh0Qy+sfCWV2H0y2Bp+wjtCNkfZHGqzxH0j87HjnLaztgneWRS0uvNUbKmy9NjCtzuQR7cd7LrhH9hQCamwpWgU/b/tO46WgaOB58R6FbWCuGeEJiHJW1eSJFijCPKzf3X8gCNQ+4TskoxfY5ksRL9sCVrJjjywp49WSM4AegvoPDRgaOOEs2v7DrNMSM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: cloudflare-api-token
      namespace: cert-manager
