apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: temporal-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  bootstrap:
    initdb:
      database: temporal
      owner: temporal
      postInitSQL:
        - CREATE DATABASE temporal_visibility OWNER temporal
  storage:
    size: 10Gi
    storageClass: proxmox-data-ext4
